// generated by koharu; do not edit

// This file has been generated by Specta. Do not edit this file manually.

import { Channel, invoke } from "./runtime";

export { Channel };

export const commands = {
  getAgentStatus: () => invoke<{
	account: Account | null,
	models: CodexModel[],
	config: Config,
	running: RunId | null,
}>("get_agent_status"),
  loginAgent: (onEvent: Channel<{ type: "progress"; message: string } | { type: "device_code"; verification_url: string; user_code: string }>) => invoke<{
	account: Account | null,
	models: CodexModel[],
	config: Config,
	running: RunId | null,
}>("login_agent", { onEvent }),
  logoutAgent: () => invoke<{
	account: Account | null,
	models: CodexModel[],
	config: Config,
	running: RunId | null,
}>("logout_agent"),
  saveAgentConfig: (config: {
	model: string | null,
	reasoning: Reasoning,
}) => invoke<{
	model: string | null,
	reasoning: Reasoning,
}>("save_agent_config", { config }),
  runAgent: (prompt: string, onEvent: Channel<{ type: "started"; run: RunId } | { type: "text_delta"; run: RunId; delta: string } | { type: "reasoning_delta"; run: RunId; delta: string } | { type: "tool_started"; run: RunId; call_id: string; name: string } | { type: "tool_finished"; run: RunId; call_id: string; name: string; changed: boolean; output: string } | { type: "completed"; run: RunId; message: string } | { type: "failed"; run: RunId; message: string } | { type: "cancelled"; run: RunId }>) => invoke<string>("run_agent", { prompt, onEvent }),
  cancelAgent: (run: string) => invoke<null>("cancel_agent", { run }),
  subscribe: (onCanvas: Channel<{
	page: EntityId | null,
	revision: Revision | null,
	generation: number,
	size: [number, number],
	element_frames: TransformFrame[],
}>, onJob: Channel<{
	id: JobId,
	kind: JobKind,
	phase: JobPhase,
	state: JobState,
	completed: number,
	total: number,
	page: EntityId | null,
	error: string | null,
}>, onDownload: Channel<{
	id: number,
	state: DownloadState,
	name: string | null,
	completed: number,
	total: number,
	error: string | null,
}>, onResources: Channel<{
	process_memory: number,
	system_memory: number,
	process_cpu: number,
	devices: DeviceResources[],
}>, onProject: Channel<{
	name: string,
	revision: Revision,
	active_page: EntityId | null,
	can_undo: boolean,
	can_redo: boolean,
} | null>) => invoke<{
	preferences: Preferences,
	jobs: Job[],
	canvas: CanvasState,
	native_dialogs: boolean,
}>("subscribe", { onCanvas, onJob, onDownload, onResources, onProject }),
  getProject: () => invoke<{
	name: string,
	revision: Revision,
	active_page: EntityId | null,
	can_undo: boolean,
	can_redo: boolean,
} | null>("get_project"),
  getPages: () => invoke<PageSummary[]>("get_pages"),
  getPage: () => invoke<{
	id: EntityId,
	label: string,
	size: PageSize,
	layers: Layer[],
	regions: AnalysisRegion[],
} | null>("get_page"),
  listProjects: () => invoke<ProjectSummary[]>("list_projects"),
  createProject: (name: string) => invoke<null>("create_project", { name }),
  openProject: (name: string) => invoke<null>("open_project", { name }),
  deleteProject: (name: string) => invoke<null>("delete_project", { name }),
  closeProject: () => invoke<null>("close_project"),
  import: (source: "files" | "folder", paths: string[] | null) => invoke<null>("import", { source, paths }),
  selectPage: (page: string) => invoke<{
	project: ProjectInfo,
	page: Page,
}>("select_page", { page }),
  renamePage: (page: string, label: string) => invoke<null>("rename_page", { page, label }),
  deletePages: (pages: EntityId[]) => invoke<null>("delete_pages", { pages }),
  movePage: (page: string, index: number) => invoke<null>("move_page", { page, index }),
  setSourceText: (layer: string, text: string) => invoke<null>("set_source_text", { layer, text }),
  setTranslation: (layer: string, text: string | null) => invoke<null>("set_translation", { layer, text }),
  setTypography: (updates: TypographyUpdate[]) => invoke<null>("set_typography", { updates }),
  setGeometry: (updates: GeometryUpdate[]) => invoke<null>("set_geometry", { updates }),
  setVisibility: (layers: EntityId[], visible: boolean | null, opacity: number | null) => invoke<null>("set_visibility", { layers, visible, opacity }),
  deleteLayers: (layers: EntityId[]) => invoke<null>("delete_layers", { layers }),
  moveLayer: (layer: string, parent: string, index: number) => invoke<{
	id: EntityId,
	label: string,
	size: PageSize,
	layers: Layer[],
	regions: AnalysisRegion[],
}>("move_layer", { layer, parent, index }),
  undo: () => invoke<null>("undo"),
  redo: () => invoke<null>("redo"),
  process: (scope: { scope: "project" } | { scope: "pages"; value: EntityId[] } | { scope: "region"; value: {
	page: EntityId,
	bounds: Bounds,
} } | { scope: "entities"; value: EntityId[] }, operation: { operation: "full" } | { operation: "through"; stage: Stage } | { operation: "only"; stage: Stage } | { operation: "stages"; stages: Stage[] }) => invoke<string>("process", { scope, operation }),
  stopJob: (job: string) => invoke<null>("stop_job", { job }),
  getGlossary: () => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("get_glossary"),
  scanGlossary: () => invoke<string>("scan_glossary"),
  setGlossaryEnabled: (expectedRevision: number, enabled: boolean) => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("set_glossary_enabled", { expectedRevision, enabled }),
  addGlossaryEntry: (expectedRevision: number, draft: {
	source: string,
	translation: string | null,
	kind: GlossaryKind,
	enabled: boolean,
}) => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("add_glossary_entry", { expectedRevision, draft }),
  updateGlossaryEntry: (expectedRevision: number, id: string, patch: {
	source: string,
	translation: string | null,
	kind: GlossaryKind,
	enabled: boolean,
}) => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("update_glossary_entry", { expectedRevision, id, patch }),
  deleteGlossaryEntries: (expectedRevision: number, ids: GlossaryEntryId[]) => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("delete_glossary_entries", { expectedRevision, ids }),
  translateGlossaryEntries: (expectedRevision: number, ids: GlossaryEntryId[] | null) => invoke<string>("translate_glossary_entries", { expectedRevision, ids }),
  previewGlossaryImport: (document: string) => invoke<{
	added: number,
	conflicting: number,
	identical: number,
	languageMismatches: LanguageMismatch[],
}>("preview_glossary_import", { document }),
  applyGlossaryImport: (expectedRevision: number, document: string, strategy: "keep_existing" | "replace_existing", confirmLanguageMismatch: boolean) => invoke<{
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
}>("apply_glossary_import", { expectedRevision, document, strategy, confirmLanguageMismatch }),
  exportGlossary: () => invoke<null>("export_glossary"),
  export: (format: "png" | "psd" | "cbz", destination: string | null) => invoke<null>("export", { format, destination }),
  getThumbnail: (page: string) => invoke<number[]>("get_thumbnail", { page }),
  getFonts: () => invoke<FontFamily[]>("get_fonts"),
  getFontPreview: (familyName: string) => invoke<number[]>("get_font_preview", { familyName }),
  savePreferences: (pipeline: {
	detection: DetectionModel,
	ocr: OcrModel,
	translation: TranslationConfig,
	inpainting: InpaintingModel,
	/**
	 *  Settings for every model are kept independently of the active model.
	 *  The active stage fields above only select which profile is used.
	 */
	processor: ProcessorConfig,
}, providers: {
	entries: ProviderPreference[],
}, typesetting: {
	font_families?: string[],
}) => invoke<{
	pipeline: PipelineConfig,
	providers: ProviderPreferences,
	typesetting: TypesettingConfig,
	languages: LanguageChoice[],
}>("save_preferences", { pipeline, providers, typesetting }),
  getPreferences: () => invoke<{
	pipeline: PipelineConfig,
	providers: ProviderPreferences,
	typesetting: TypesettingConfig,
	languages: LanguageChoice[],
}>("get_preferences"),
  getTranslationModels: () => invoke<Model[]>("get_translation_models"),
  getCanvasManifest: (generation: number) => invoke<number[]>("get_canvas_manifest", { generation }),
  getCanvasResource: (generation: number, resource: string) => invoke<number[]>("get_canvas_resource", { generation, resource }),
  prepareCanvasPage: (page: string) => invoke<{
	revision: Revision,
	page: Page,
} | null>("prepare_canvas_page", { page }),
  getCanvasPageManifest: (page: string, revision: number) => invoke<number[]>("get_canvas_page_manifest", { page, revision }),
  getCanvasPageResource: (page: string, revision: number, resource: string) => invoke<number[]>("get_canvas_page_resource", { page, revision, resource }),
  addPointText: (point: {
	x: number,
	y: number,
}) => invoke<{
	revision: Revision,
	layer: EntityId,
}>("add_point_text", { point }),
  addTextBox: (frame: {
	x: number,
	y: number,
	width: number,
	height: number,
	angle_degrees: number,
}) => invoke<{
	revision: Revision,
	layer: EntityId,
}>("add_text_box", { frame }),
  commitPaint: (expectedRevision: number, layer: string | null, points: Point[], brush: {
	diameter: number,
	color: [number, number, number, number],
}) => invoke<{
	revision: Revision,
	layer: EntityId,
}>("commit_paint", { expectedRevision, layer, points, brush }),
  commitErase: (expectedRevision: number, layer: string, points: Point[], diameter: number | null) => invoke<{
	revision: Revision,
	layer: EntityId,
}>("commit_erase", { expectedRevision, layer, points, diameter }),
  commitTransform: (expectedRevision: number, elements: TransformFrame[]) => invoke<number | null>("commit_transform", { expectedRevision, elements }),
  commitInpaint: (expectedRevision: number, points: Point[], diameter: number | null) => invoke<string | null>("commit_inpaint", { expectedRevision, points, diameter }),
};

export type Account = {
	id: string,
	email: string | null,
	plan: string | null,
};

export type AgentStatus = {
	account: Account | null,
	models: CodexModel[],
	config: Config,
	running: RunId | null,
};

export type AnalysisRegion = {
	id: EntityId,
	parent: EntityId | null,
	geometry: Geometry,
	kind: string,
	label: string | null,
};

export type Bounds = {
	x: number,
	y: number,
	width: number,
	height: number,
};

export type CaiyunConfig = Record<string, never>;

export type CanvasBytes = number[];

export type CanvasGeneration = number;

export type CanvasPagePreparation = {
	revision: Revision,
	page: Page,
};

export type CanvasState = {
	page: EntityId | null,
	revision: Revision | null,
	generation: number,
	size: [number, number],
	element_frames: TransformFrame[],
};

export type ClaudeConfig = Record<string, never>;

export type CodexModel = {
	id: string,
	name: string,
	reasoning: Reasoning[],
};

export type Config = {
	model: string | null,
	reasoning: Reasoning,
};

export type CredentialInput = {
	configured: boolean,
	value: string | null,
	clear: boolean,
};

export type DeepLConfig = {
	base_url?: string | null,
};

export type DeepSeekConfig = Record<string, never>;

export type DetectionModel = {
	model: "koharu-layout-rfdetr-seg-2xl",
} & KoharuLayoutRFDetrSeg2XLConfig;

export type DeviceResources = {
	name: string,
	selected: boolean,
	memory_budget: number | null,
	memory_used: number | null,
	utilization: number | null,
};

export type Download = {
	id: number,
	state: DownloadState,
	name: string | null,
	completed: number,
	total: number,
	error: string | null,
};

export type DownloadState = "running" | "finished" | "failed";

export type EntityId = string;

export type Event = { type: "started"; run: RunId } | { type: "text_delta"; run: RunId; delta: string } | { type: "reasoning_delta"; run: RunId; delta: string } | { type: "tool_started"; run: RunId; call_id: string; name: string } | { type: "tool_finished"; run: RunId; call_id: string; name: string; changed: boolean; output: string } | { type: "completed"; run: RunId; message: string } | { type: "failed"; run: RunId; message: string } | { type: "cancelled"; run: RunId };

export type ExportFormat = "png" | "psd" | "cbz";

export type Flux2KleinConfig = {
	prompt?: string,
};

export type FontFace = {
	postscript_name: string,
	weight: number,
	weight_range: FontRange | null,
	style: FontStyle,
};

export type FontFamily = {
	name: string,
	metadata: FontMetadata,
	sources: FontSource[],
	faces: FontFace[],
};

export type FontMetadata = {
	primary_script: string | null,
	scripts: string[],
	languages: string[],
	category: string | null,
	classifications: string[],
	use_cases: string[],
};

export type FontPreviewBytes = number[];

export type FontRange = {
	minimum: number,
	maximum: number,
};

export type FontSource = "system" | "bundled";

export type FontStyle = "normal" | "italic" | "oblique";

export type Frame = {
	x: number,
	y: number,
	width: number,
	height: number,
	angle_degrees: number,
};

export type GeminiConfig = Record<string, never>;

export type GenerationConfig = {
	temperature?: number | null,
	top_k?: number | null,
	top_p?: number | null,
	min_p?: number | null,
	max_tokens?: number | null,
	repeat_penalty?: number | null,
	frequency_penalty?: number | null,
	presence_penalty?: number | null,
	reasoning?: boolean | null,
	vision?: boolean | null,
};

export type Geometry = {
	points: Point[],
};

export type GeometryUpdate = {
	layer: EntityId,
	points: Point[] | null,
};

export type GlossaryEntryDraft = {
	source: string,
	translation: string | null,
	kind: GlossaryKind,
	enabled: boolean,
};

export type GlossaryEntryId = string;

export type GlossaryEntryPatch = {
	source: string,
	translation: string | null,
	kind: GlossaryKind,
	enabled: boolean,
};

export type GlossaryEntryView = {
	revision: Revision,
	id: GlossaryEntryId,
	source: string,
	translation: string | null,
	kind: GlossaryKind,
	enabled: boolean,
	confidence: number | null,
	occurrenceCount: number,
	examples: string[],
	sourceOrigin: GlossaryValueOrigin,
	translationOrigin: GlossaryValueOrigin | null,
	presentInLastScan: boolean,
};

export type GlossaryImportPreview = {
	added: number,
	conflicting: number,
	identical: number,
	languageMismatches: LanguageMismatch[],
};

export type GlossaryImportStrategy = "keep_existing" | "replace_existing";

export type GlossaryKind = "person" | "place" | "organization" | "item" | "ability" | "term" | "other";

export type GlossaryValueOrigin = "detected" | "automatic" | "user" | "imported";

export type GlossaryView = {
	revision: Revision,
	enabled: boolean,
	stale: boolean,
	sourceLanguage: LanguageTag | null,
	targetLanguage: LanguageTag | null,
	savedSourceFingerprint: string | null,
	currentSourceFingerprint: string,
	entries: GlossaryEntryView[],
};

export type GoogleCloudConfig = Record<string, never>;

export type GrokConfig = Record<string, never>;

export type GroupRole = "text";

export type InpaintingModel = { model: "lama" } | { model: "aot-inpainting" } | {
	model: "flux2-klein",
} & Flux2KleinConfig | {
	model: "rorem-mixed",
} & RoremMixedConfig;

export type Job = {
	id: JobId,
	kind: JobKind,
	phase: JobPhase,
	state: JobState,
	completed: number,
	total: number,
	page: EntityId | null,
	error: string | null,
};

export type JobId = string;

export type JobKind = "pipeline" | "glossary_scan" | "glossary_translation";

export type JobPhase = { kind: "pipeline"; stage: Stage | null } | { kind: "preparing_ocr" } | { kind: "extracting_terms" } | { kind: "translating_terms" };

export type JobState = "running" | "finished" | "failed" | "stopped";

export type KoharuLayoutRFDetrSeg2XLConfig = {
	text_threshold?: number | null,
	bubble_threshold?: number | null,
	panel_threshold?: number | null,
};

export type LanguageChoice = {
	tag: string,
	name: string,
};

export type LanguageField = "source" | "target";

export type LanguageMismatch = {
	field: LanguageField,
	current: LanguageTag | null,
	imported: LanguageTag | null,
};

export type LanguageTag = string;

export type Layer = { type: "group"; id: EntityId; parent: EntityId | null; visibility: LayerVisibility; name: string; role: GroupRole | null } | { type: "text"; id: EntityId; parent: EntityId | null; geometry: Geometry | null; angle_degrees: number | null; visibility: LayerVisibility; content: TextContent; typography: Typography | null; layout: TextLayoutKind; automatic_region: EntityId | null } | { type: "raster"; id: EntityId; parent: EntityId | null; visibility: LayerVisibility; image: string | null; name: string; kind: RasterLayerKind } | { type: "image"; id: EntityId; parent: EntityId | null; geometry: Geometry; visibility: LayerVisibility; image: string } | { type: "artwork"; id: EntityId; parent: EntityId | null; geometry: Geometry; visibility: LayerVisibility; image: string };

export type LayerCommit = {
	revision: Revision,
	layer: EntityId,
};

export type LayerVisibility = {
	visible: boolean,
	opacity: number,
};

export type LmStudioConfig = {
	base_url?: string | null,
};

export type LocalConfig = Record<string, never>;

export type LoginEvent = { type: "progress"; message: string } | { type: "device_code"; verification_url: string; user_code: string };

export type MiniMaxConfig = Record<string, never>;

export type Model = {
	provider: Provider,
	model: string | null,
	name: string,
	quantizations: Quantization[],
	vision: boolean,
	reasoning: boolean,
};

export type ModelResources = {
	process_memory: number,
	system_memory: number,
	process_cpu: number,
	devices: DeviceResources[],
};

export type ModelSelection = {
	provider: Provider,
	model?: string | null,
	quantization?: string | null,
	vision?: boolean,
	reasoning?: boolean,
};

export type OcrModel = { model: "paddleocr-vl-1.6" } | { model: "manga-ocr" } | { model: "baberu-ocr" } | { model: "hayai-ocr" };

export type OpenAiCompatibleConfig = {
	base_url?: string | null,
};

export type OpenAiConfig = Record<string, never>;

export type OpenRouterConfig = Record<string, never>;

export type Operation = { operation: "full" } | { operation: "through"; stage: Stage } | { operation: "only"; stage: Stage } | { operation: "stages"; stages: Stage[] };

export type Page = {
	id: EntityId,
	label: string,
	size: PageSize,
	layers: Layer[],
	regions: AnalysisRegion[],
};

export type PageImportSource = "files" | "folder";

export type PageSelection = {
	project: ProjectInfo,
	page: Page,
};

export type PageSize = {
	width: number,
	height: number,
};

export type PageSummary = {
	id: EntityId,
	label: string,
	size: PageSize,
	source_asset: string | null,
	layer_count: number,
};

export type PaintBrush = {
	diameter: number,
	color: [number, number, number, number],
};

export type PipelineConfig = {
	detection: DetectionModel,
	ocr: OcrModel,
	translation: TranslationConfig,
	inpainting: InpaintingModel,
	/**
	 *  Settings for every model are kept independently of the active model.
	 *  The active stage fields above only select which profile is used.
	 */
	processor: ProcessorConfig,
};

export type Point = {
	x: number,
	y: number,
};

export type Preferences = {
	pipeline: PipelineConfig,
	providers: ProviderPreferences,
	typesetting: TypesettingConfig,
	languages: LanguageChoice[],
};

export type ProcessorConfig = {
	"koharu-layout-rfdetr-seg-2xl"?: KoharuLayoutRFDetrSeg2XLConfig | null,
	"flux2-klein"?: Flux2KleinConfig | null,
	"rorem-mixed"?: RoremMixedConfig | null,
};

export type ProjectInfo = {
	name: string,
	revision: Revision,
	active_page: EntityId | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectSummary = {
	name: string,
};

export type Provider = "local" | "openai" | "gemini" | "claude" | "grok" | "minimax" | "deepseek" | "openai-compatible" | "openrouter" | "lm-studio" | "deepl" | "google-cloud-translation" | "caiyun";

export type ProviderConfig = { provider: "local"; settings: LocalConfig } | { provider: "openai"; settings: OpenAiConfig } | { provider: "gemini"; settings: GeminiConfig } | { provider: "claude"; settings: ClaudeConfig } | { provider: "grok"; settings: GrokConfig } | { provider: "minimax"; settings: MiniMaxConfig } | { provider: "deepseek"; settings: DeepSeekConfig } | { provider: "openai-compatible"; settings: OpenAiCompatibleConfig } | { provider: "openrouter"; settings: OpenRouterConfig } | { provider: "lm-studio"; settings: LmStudioConfig } | { provider: "deepl"; settings: DeepLConfig } | { provider: "google-cloud-translation"; settings: GoogleCloudConfig } | { provider: "caiyun"; settings: CaiyunConfig };

export type ProviderPreference = {
	name: string,
	config: ProviderConfig,
	credential: CredentialInput | null,
};

export type ProviderPreferences = {
	entries: ProviderPreference[],
};

export type Quantization = {
	id: string,
	name: string,
	downloaded: boolean,
};

export type RasterLayerKind = "cleanup" | "paint";

export type Reasoning = "low" | "medium" | "high" | "xhigh" | "max" | "ultra";

export type Revision = number;

export type RoremMixedConfig = {
	prompt?: string,
	negative_prompt?: string,
};

export type RunId = string;

export type Scope = { scope: "project" } | { scope: "pages"; value: EntityId[] } | { scope: "region"; value: {
	page: EntityId,
	bounds: Bounds,
} } | { scope: "entities"; value: EntityId[] };

export type SourceText = {
	text: string,
	language: string | null,
};

export type Stage = "detection" | "ocr" | "translation" | "inpainting";

export type StartupState = {
	preferences: Preferences,
	jobs: Job[],
	canvas: CanvasState,
	native_dialogs: boolean,
};

export type TextAlignment = "Start" | "Center" | "End" | "Justify";

export type TextContent = {
	id: EntityId,
	source: SourceText | null,
	translation: Translation | null,
	role: string | null,
	source_region: EntityId | null,
};

export type TextLayoutKind = "point" | "paragraph";

export type ThumbnailBytes = number[];

export type TransformFrame = {
	element: EntityId,
	frame: Frame,
};

export type Translation = {
	text: string,
	language: string | null,
};

export type TranslationConfig = {
	model: ModelSelection,
	generation: GenerationConfig,
	target_language: string,
	instructions: string | null,
};

export type TypesettingConfig = {
	font_families?: string[],
};

export type Typography = {
	preferred_font: string | null,
	font_weight: number | null,
	font_style: FontStyle | null,
	size: number | null,
	auto_fit: boolean,
	color: [number, number, number, number] | null,
	stroke_color: [number, number, number, number] | null,
	stroke_width: number | null,
	alignment: TextAlignment | null,
	writing_mode: WritingMode | null,
};

export type TypographyUpdate = {
	layer: EntityId,
	typography: Typography,
};

export type WritingMode = "Horizontal" | "Vertical";
